/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

val otelVersion = "1.56.0"

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    implementation("io.opentelemetry:opentelemetry-sdk:${otelVersion}")
    implementation("io.opentelemetry:opentelemetry-sdk-logs:${otelVersion}")
    implementation("io.opentelemetry:opentelemetry-exporter-otlp:${otelVersion}")

    implementation("ch.qos.logback:logback-classic:1.5.19")
    implementation("io.opentelemetry.instrumentation:opentelemetry-logback-appender-1.0:2.22.0-alpha")

    implementation("io.opentelemetry:opentelemetry-api-logs:1.26.0-alpha")
    implementation("io.opentelemetry:opentelemetry-exporter-otlp-logs:1.26.0-alpha")

//    implementation("io.opentelemetry.semconv:opentelemetry-semconv:1.37.0")
//    implementation("io.opentelemetry.semconv:opentelemetry-semconv-incubating:1.37.0-alpha")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.AppKt"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
